name: aw_router
description: A lightweight, composable, and middleware-friendly router designed for use with Appwrite Cloud Functions.
repository: https://github.com/Weav3r/aw_router
issue_tracker: https://github.com/Weav3r/aw_router/issues
version: 0.1.0-beta

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
